
# This file is used to configure your Supabase project.
# Learn more: https://supabase.com/docs/reference/cli/config

[storage]
[[storage.buckets]]
name = "client_photos"
public = true
file_size_limit = "5MB"
allowed_mime_types = ["image/png", "image/jpeg", "image/jpg", "image/gif", "image/webp"]

[functions.process-migration]
verify_jwt = true

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false
